models/colaboradores.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "colaboradores".
 *
 * @property int $id
 * @property string|null $nombre
 * @property string|null $rs
 * @property string|null $dir
 * @property int|null $cp
 * @property string|null $pob
 * @property int|null $movil
 * @property string|null $email
 * @property string|null $tipo
 * @property string|null $alta
 * @property string|null $baja
 * @property string|null $observaciones
 *
 * @property Visualiza[] $visualizas
 */
class colaboradores extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'colaboradores';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cp', 'movil'], 'integer'],
            [['alta', 'baja'], 'safe'],
            [['observaciones'], 'string'],
            [['nombre', 'rs', 'pob', 'email', 'tipo'], 'string', 'max' => 100],
            [['dir'], 'string', 'max' => 200],
            [['tipo'], 'string', 'max' => 100],
            [['tipoCliente'], 'string', 'max' => 100],
            [['provincia'], 'string', 'max' => 100],
            [['afluencia'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'rs' => 'Rs',
            'dir' => 'Dir',
            'cp' => 'Cp',
            'pob' => 'Pob',
            'movil' => 'Movil',
            'email' => 'Email',
            'tipo' => 'Tipo',
            'tipoCliente' => 'TipoCliente',
            'provincia' => 'Provincia',
            'afluencia' => 'Afluencia',
            'alta' => 'Alta',
            'baja' => 'Baja',
            'observaciones' => 'Observaciones',
            
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVisualizas()
    {
        return $this->hasMany(Visualiza::className(), ['colaborador' => 'id']);
    }
}

controllers/ColaboradoresController.php
<?php

namespace app\controllers;

use Yii;
use app\models\colaboradores;
use app\models\ColaboradoresSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use app\models\filtroEstable;
use app\models\visualiza;


/**
 * ColaboradoresController implements the CRUD actions for colaboradores model.
 */
class ColaboradoresController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all colaboradores models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ColaboradoresSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single colaboradores model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new colaboradores model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new colaboradores();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing colaboradores model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing colaboradores model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the colaboradores model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return colaboradores the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = colaboradores::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    
    
 public function actionFiltrar(){
     
 
         $model = new filtroEstable();
       
     
     return $this->render('establecimientos',['model' => $model]);
   
 }
 

 
 public function actionEstablecimientos(){
     $model = new filtroEstable();
    
    $model->load(\Yii::$app->request->post());


if ($model->tipoEstablecimiento || $model->tipoCliente || $model->afluencia || $model->provincia || $model->activo) {
       
    
          $tipoEstablecimiento = $model->tipoEstablecimiento;
          $tipoCliente = $model->tipoCliente; 
          $afluencia = $model->afluencia;
          $provincia = $model->provincia;
          $activo = $model->activo;
          
//          if ($tipoEstablecimiento<>""){
//              $filtro = " where tipo = '$tipoEstablecimiento'";
//          } 
              if ($activo <>""){
                   $filtro = " and tipo = '$tipoEstablecimiento'";
              }else{
                  $filtro = " WHERE tipo = '$tipoEstablecimiento'";
              }
          
           if ($tipoCliente<>""){
              $filtro .= " and tipoCliente = '$tipoCliente'";
          } 
           if ($afluencia<>""){
              $filtro .= " and afluencia = '$afluencia'";
          } 
            if ($provincia<>""){
              $filtro .= " and provincia = '$provincia'";
          } 
          if ($activo <>""){
              if($activo == 1){
                  //activo
                  $sql = "
                        SELECT cola.id id,cola.nombre nombre, cola.dir dir, cola.email email, cola.pob pob FROM colaboradores cola LEFT join visualiza visu ON cola.id = visu.colaborador WHERE visu.colaborador IS NULL$filtro
                        UNION
                        SELECT cola.id id,cola.nombre nombre, cola.dir dir, cola.email email, cola.pob pob FROM colaboradores cola JOIN visualiza visu ON cola.id = visu.colaborador WHERE visu.fincontrato < CURRENT_DATE()$filtro";
          
              }else{
                  //inactivo
                  $sql = "SELECT cola.id id,cola.nombre nombre, cola.dir dir, cola.email email, cola.pob pob FROM colaboradores cola join visualiza visu ON cola.id = visu.colaborador WHERE visu.fincontrato > CURRENT_DATE()$filtro";
                  
              }
          }else{
              $sql = "SELECT cola.id id,cola.nombre nombre, cola.dir dir, cola.email email, cola.pob pob FROM colaboradores cola
                       $filtro";
          }
          
//           if ($activo=0){
//              $filtro .= " and fecha = ";
//          } 
//           if ($activo=1){
//              $filtro .= " and fecha = ";
//          } 
//          echo("Tipo de establecimiento:".$tipoEstablecimiento);
//          echo("Tipo de Cliente: ".$tipocliente);
//          echo("Afluencia: ".$afluencia);
//          echo("Provincia: ".$provincia);
//          exit;
//          $dataProvider = new SqlDataProvider([
                              
               
          
//          $datos = Colaboradores::find()
//                  ->all();
        
         $datos = new SqlDataProvider([
                    'sql' => $sql]);
//         $datos1 = $datos->getModels();
               
          
              
        return $this->render('establecimientos', [
            "dataProvider" => $datos,
            "model"=>$model,
            "campos"=>['id','nombre','dir','email','pob'],
            "titulo"=>"Listado de establecimientos",
            "enunciado"=>"Establecimientos",
           
          ]);
       
      }else{
          $dataProvider = Null;
          
          return $this->render('establecimientos',['model' => $model,"dataProvider" => $dataProvider]);
    }
}  
}

views/colaboradores/_colaboradores.php
<?php
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\data\ActiveDataProvider;
 

$this->title = "Establecimientos";

//$this->params['breadcrumbs'][] = ['label' => 'Autores', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
//\yii\web\YiiAsset::register($this);

$options = ['style' => ['width' => '290px', 'height' => '200px']];

?>


<div class="establecimientos-view">
   
 
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
          
          <div style=""> <?= Html::img("@web/img_colaboradores/".$model['id'].".jpg", $options)?></div>
       
        <h3><?= $model['nombre']?></h3>
        <p><?= $model['dir']?></p>
        <p><?= $model['pob'] ?></p>
        <?php
        if(isset($model['movil'])){?>
        <p><?= $model['movil'] ?></p>
        <?php
        }
        ?>
   
        <?= Html::a('Ver Establecimiento', ['colaboradores/establecimientos'], ['class' => 'btn btn-primary btn-md', 'style'=>'margin-top:10px;']) ?>
       
      </div>
    </div>
  </div>
    
</div>

views/colaboradores/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\colaboradores */
/* @var $form yii\widgets\ActiveForm */
$itemsEstablecimientos =  array('Bar'=>'Bar','Cafetería'=>'Cafetería','Restaurante'=>'Restaurante','Pub'=>'Pub'); 
$itemsClientes =  array('Estudiantes'=>'Estudiantes','Familias'=>'Familias','Jubilados'=>'Jubilados'); 
$itemsAfluencia = array('Mañanas'=>'Mañanas','Tardes'=>'Tardes','Noches'=>'Noches'); 
$itemsProvincias =  array('Alava'=>'Alava','Albacete'=>'Albacete','Alicante'=>'Alicante','Almería'=>'Almería','Asturias'=>'Asturias','Avila'=>'Avila','Badajoz'=>'Badajoz','Barcelona'=>'Barcelona','Burgos'=>'Burgos','Cáceres'=>'Cáceres',
                        'Cádiz'=>'Cádiz','Cantabria'=>'Cantabria','Castellón'=>'Castellón','Ciudad Real'=>'Ciudad Real','Córdoba'=>'Córdoba','La Coruña'=>'La Coruña','Cuenca'=>'Cuenca','Gerona'=>'Gerona','Granada'=>'Granada','Guadalajara'=>'Guadalajara',
                        'Guipúzcoa'=>'Guipúzcoa','Huelva'=>'Huelva','Huesca'=>'Huesca','Islas Baleares'=>'Islas Baleares','Jaén'=>'Jaén','León'=>'León','Lérida'=>'Lérida','Lugo'=>'Lugo','Madrid'=>'Madrid','Málaga'=>'Málaga','Murcia'=>'Murcia','Navarra'=>'Navarra',
                        'Orense'=>'Orense','Palencia'=>'Palencia','Las Palmas'=>'Las Palmas','Pontevedra'=>'Pontevedra','La Rioja'=>'La Rioja','Salamanca'=>'Salamanca','Segovia'=>'Segovia','Sevilla'=>'Sevilla','Soria'=>'Soria','Tarragona'=>'Tarragona',
                        'Santa Cruz de Tenerife'=>'Santa Cruz de Tenerife','Teruel'=>'Teruel','Toledo'=>'Toledo','Valencia'=>'Valencia','Valladolid'=>'Valladolid','Vizcaya'=>'Vizcaya','Zamora'=>'Zamora','Zaragoza'=>'Zaragoza');
?>

<div class="colaboradores-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'rs')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dir')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cp')->textInput() ?>

    <?= $form->field($model, 'pob')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'movil')->textInput() ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo')->dropDownList($itemsEstablecimientos, ['prompt' => 'Seleccione Uno' ]); ?>
    
     <?= $form->field($model, 'tipoCliente')->dropDownList($itemsClientes, ['prompt' => 'Seleccione Uno' ]); ?>
    
     <?= $form->field($model, 'provincia')->dropDownList($itemsProvincias, ['prompt' => 'Seleccione Uno' ]); ?>
    
     <?= $form->field($model, 'afluencia')->dropDownList($itemsAfluencia, ['prompt' => 'Seleccione Uno' ]); ?>
    


    
     <?= $form->field($model, 'alta')->widget(DatePicker::className(), [
            // inline too, not bad
            'inline' => false, 
             // modify template for custom rendering
            //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
            'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd-mm-yyyy',
            'todayBtn' => true
            ]
    ]);?>

    

    
     <?= $form->field($model, 'baja')->widget(DatePicker::className(), [
            // inline too, not bad
            'inline' => false, 
             // modify template for custom rendering
            //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
            'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd-mm-yyyy',
            'todayBtn' => true
            ]
    ]);?>

    

    <?= $form->field($model, 'observaciones')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/colaboradores/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ColaboradoresSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="colaboradores-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'rs') ?>

    <?= $form->field($model, 'dir') ?>

    <?= $form->field($model, 'cp') ?>

    <?php // echo $form->field($model, 'pob') ?>

    <?php // echo $form->field($model, 'movil') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'tipo') ?>
     <?= $form->field($model, 'tipoCliente') ?>
    
     <?= $form->field($model, 'provincia') ?>
    
     <?= $form->field($model, 'afluencia') ?>

    <?php // echo $form->field($model, 'alta') ?>

    <?php // echo $form->field($model, 'baja') ?>

    <?php // echo $form->field($model, 'observaciones') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/colaboradores/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\colaboradores */

$this->title = 'Create Colaboradores';
$this->params['breadcrumbs'][] = ['label' => 'Colaboradores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="colaboradores-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/colaboradores/establecimientos.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\widgets\ListView;
use app\models\filtroEstable;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;


$this->registerCssFile('@web/css/filtros.css', ['depends' => [yii\bootstrap\BootstrapAsset::className()]]);

?>

   
<div class="jumbotron-fluid text-center bg-success">
  <h1>Listado de Establecimientos</h1>
  
</div>

<div class="container" style="margin-left:-200px;margin-top:50px;border-radius:5px;border:1px solid grey;width: 275px;display:flex;flex-direction: column;justify-content: space-around;">
<!--<div class="establecimientos-view">-->

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="form-group col-md-12" style="margin-top: -15px;">
        
        <?php $form = ActiveForm::begin([
            'method' => 'post',
            'id' => 'formulario',
            'enableClientValidation' => true,
            'enableAjaxValidation' => false,
            'action'=>'establecimientos',
           ]); ?>
           

   
       <?= $form->field($model,'tipoEstablecimiento')->dropDownList(
               array(''=>'','Bar'=>'Bar','Cafetería'=>'Cafetería','Restaurante'=>'Restaurante','Pub'=>'Pub'),
               $options=['class'=>'form-control form-control-lg', 'style'=>'width:200px'])->label('Tipo Etablecimiento');?>

        <?= $form->field($model,'tipoCliente')->dropDownList(
                array(''=>'','Estudiantes'=>'Estudiantes','Familias'=>'Familias','Jubilados'=>'Jubilados'),
                $options=['class'=>'form-control form-control-lg', 'style'=>'width:200px'])->label('Tipo Cliente');?>
            
        <?= $form->field($model,'afluencia')->dropDownList(
                array(''=>'','Mañanas'=>'Mañanas','Tardes'=>'Tardes','Noches'=>'Noches'),
                $options=['class'=>'form-control form-control-lg', 'style'=>'width:200px'])->label('Afluencia');?>
        
        
        <?= $form->field($model,'provincia')->dropDownList(
                array(''=>'','Alava'=>'Alava','Albacete'=>'Albacete','Alicante'=>'Alicante','Almería'=>'Almería','Asturias'=>'Asturias','Avila'=>'Avila','Badajoz'=>'Badajoz','Barcelona'=>'Barcelona','Burgos'=>'Burgos','Cáceres'=>'Cáceres',
                        'Cádiz'=>'Cádiz','Cantabria'=>'Cantabria','Castellón'=>'Castellón','Ciudad Real'=>'Ciudad Real','Córdoba'=>'Córdoba','La Coruña'=>'La Coruña','Cuenca'=>'Cuenca','Gerona'=>'Gerona','Granada'=>'Granada','Guadalajara'=>'Guadalajara',
                        'Guipúzcoa'=>'Guipúzcoa','Huelva'=>'Huelva','Huesca'=>'Huesca','Islas Baleares'=>'Islas Baleares','Jaén'=>'Jaén','León'=>'León','Lérida'=>'Lérida','Lugo'=>'Lugo','Madrid'=>'Madrid','Málaga'=>'Málaga','Murcia'=>'Murcia','Navarra'=>'Navarra',
                        'Orense'=>'Orense','Palencia'=>'Palencia','Las Palmas'=>'Las Palmas','Pontevedra'=>'Pontevedra','La Rioja'=>'La Rioja','Salamanca'=>'Salamanca','Segovia'=>'Segovia','Sevilla'=>'Sevilla','Soria'=>'Soria','Tarragona'=>'Tarragona',
                        'Santa Cruz de Tenerife'=>'Santa Cruz de Tenerife','Teruel'=>'Teruel','Toledo'=>'Toledo','Valencia'=>'Valencia','Valladolid'=>'Valladolid','Vizcaya'=>'Vizcaya','Zamora'=>'Zamora','Zaragoza'=>'Zaragoza'),
                
                $options=['class'=>'form-control form-control-lg', 'style'=>'width:200px'])->label('Provincias');?>
        
           <?= $form->field($model,'activo')->dropDownList(
                array(''=>'','0'=>'Inactivo','1'=>'Activo'),
                $options=['class'=>'form-control form-control-lg', 'style'=>'width:200px'])->label('Estado');?>
        
    </div>   
        <div class="form-group col-md-12">
            <?= Html::submitButton("filtrar", ["class" => "btn btn-primary","style"=>"width:200px;font-size:20px"]) ?>
    <!--            
           Html::submitButton('Emitir',
                    ['class'=>'btn btn-primary btn-lg active',

                        'style'=>'width:300px',
                        'data-toggle'=>'tooltip',
                        'title'=>Yii::t('app', 'Emisión de Recibos Mensual'),
                    ]
                )-->
        </div>
    <!--</div>-->
    
    
    
 </div>   
    <?php ActiveForm::end(); ?>

<div style="position: relative;top:-490px;padding-top:10px;padding-left:100px;">

    <?php
    if (isset($dataProvider)){
        
//         foreach ($dataProvider->getModels() as $model) {
             echo ListView::widget([
                 'dataProvider' => $dataProvider,
                 'itemView' => '_colaboradores',  
                  
             ]);
}
?>
    
</div>

</body>
</html>

 

 






<!--<div class="well well-sm"><h2 style="text-align: center;max-height: 50px;"></h2></div>-->

views/colaboradores/establecimientos_1.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\widgets\ListView;
use app\models\filtroEstable;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;




?>
<div class="jumbotron-fluid text-center bg-success">
  <h1>Listado de Establecimientos</h1>
 
</div>

<div class="container" style="margin-left: 290px;margin-top:50px;border-radius:5px;border:1px solid grey;width: 530px;">
<div class="establecimientos-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="form-group col-md-12">
        
     

<div class="row">
   
    <?php
   
   
        
    
        ListView::widget([
            'dataProvider' => $datos,
            'itemView' => '_colaboradores',
            'layout'=>"{summary}\n{pager}\n{items}",
            'model'=>$model,
           
        ]);

?>
    
</div>
   
</body>
</html>

 

 






<!--<div class="well well-sm"><h2 style="text-align: center;max-height: 50px;"></h2></div>-->

views/colaboradores/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ColaboradoresSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Colaboradores';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="colaboradores-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Colaboradores', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'rs',
            'dir',
            'cp',
            //'pob',
            //'movil',
            //'email:email',
            'tipo',
            'tipoCliente',
            'provincia',
            'afluencia',
            //'alta',
            //'baja',
            //'observaciones:ntext',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/colaboradores/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\colaboradores */

$this->title = 'Update Colaboradores: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Colaboradores', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="colaboradores-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/colaboradores/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\colaboradores */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Colaboradores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="colaboradores-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'rs',
            'dir',
            'cp',
            'pob',
            'movil',
            'email:email',
            'tipo',
            'tipoCliente',
            'provincia',
            'afluencia',
            'alta',
            'baja',
            'observaciones:ntext',
        ],
    ]) ?>

</div>